function handles = addtabRegistrationcontrols( parent, handles )
%ADDTABREGISTRATIONCONTROLS Summary of this function goes here
%   Detailed explanation goes here

vBoxLeft = uix.VBox('Parent', parent, ...
    'Padding', 5, ...
    'Spacing', 5);
vBoxRight = uix.VBox('Parent', parent, ...
    'Padding', 5, ...
    'Spacing', 5);

% Set widths of the main GUI columns
set(parent, 'Widths', [ -2 -1 ]);

registrationPanel = uix.Panel('Parent', vBoxRight, ...
    'Padding', 5);

localizerGrid = uix.Grid('Parent', registrationPanel, ...
    'Spacing', 5);

uicontrol('Parent', localizerGrid, ...
    'Style', 'text', ...
    'String', 'Shift X');

uicontrol('Parent', localizerGrid, ...
    'Style', 'text', ...
    'String', 'Shift Y');

uicontrol('Parent', localizerGrid, ...
    'Style', 'text', ...
    'String', 'Binsize');

uicontrol('Parent', localizerGrid, ...
    'Style', 'pushbutton', ...
    'String', 'Do it!', ...
    'Callback', @onRegister);

uicontrol('Parent', localizerGrid, ...
    'Style', 'edit', ...
    'String', '0.0e-009', ...
    'Tag', 'ShiftX');

uicontrol('Parent', localizerGrid, ...
    'Style', 'edit', ...
    'String', '0.0e-009', ...
    'Tag', 'ShiftY');

uicontrol('Parent', localizerGrid, ...
    'Fontweight', 'bold', ...
    'Style', 'edit', ...
    'String', '50.0e-009', ...
    'Tag', 'BinSize');

uix.Empty( 'Parent', localizerGrid )

set(localizerGrid, 'Widths', [ -1 -0.5 ], 'Heights', [ 25 25 25 25 ]);

handles.registrationCtrls = registrationPanel;

end

