function onRegister( source , callbackdata )
%ONREGISTER Summary of this function goes here
%   Detailed explanation goes here

[ ~, handles ] = getmainwindowhandles();

ShiftX = str2double(getuicontrolstring(handles.registrationCtrls, 'ShiftX'));
ShiftY = str2double(getuicontrolstring(handles.registrationCtrls, 'ShiftY'));
BinSize = str2double(getuicontrolstring(handles.registrationCtrls, 'BinSize'));

% For debug only: Plug in some coordinates of the events here...
%handles.XYEvents = [ 414 53; 23 220 ];
%handles.XYEvents = handles.XYSEM;

[ transformedpoints, ~ ] = clemcorrelation( ...
    handles.XYSEM, ...
    handles.XYCL, ...
    handles.XYEvents(:, [ 2 3 ]) );

if handles.imagemode
    performimageoverlay( ...
        handles.imageSEMO, ...
        handles.infoSEMO, ... 
        handles.imageSEMZ, ...
        handles.infoSEMZ, ...
        ShiftX, ...
        ShiftY)
else
    performoverlay( ...
        transformedpoints, ...
        handles.imageSEMO, ...
        handles.infoSEMO, ... 
        handles.imageSEMZ, ...
        handles.infoSEMZ, ...
        ShiftX, ...
        ShiftY, ...
        BinSize)
end

setmainwindowhandles(handles);

end

